theme: jekyll-theme-modernist
title: [macosgame studio]
description: ["Email:<a href='mailto:macosgamedeveloper@icloud.com'>macosgamedeveloper@icloud.com</a>"]
# Google Analytics
google_analytics: UA-247615188-1
